#!/usr/bin/env python3
import os
import os.path
"""Coder Agent with Phi3 (Microsoft) - Better quality than 0.5B"""
import json, subprocess, sys, os, time

WORKSPACE = os.path.expanduser('~/.openclaw/workspace')
MODEL = 'phi3:mini'

def log_metrics(task_id, tokens_in, tokens_out, eval_time):
    cost = 0.0  # Local = free
    subprocess.run([f'{WORKSPACE}/llm-observability.sh', 'log', task_id, 'coder', MODEL, 
                   str(tokens_in), str(tokens_out), str(eval_time), str(cost)], capture_output=True)

def call_phi3(prompt):
    start = time.time()
    try:
        result = subprocess.run(['ollama', 'run', MODEL], input=prompt, capture_output=True, text=True, timeout=90)
        elapsed = int((time.time() - start) * 1000)
        return {
            'response': result.stdout.strip(),
            'tokens_in': len(prompt)//4,
            'tokens_out': len(result.stdout)//4,
            'eval_time': elapsed,
            'success': result.returncode == 0
        }
    except Exception as e:
        return {'response': str(e), 'tokens_in': 0, 'tokens_out': 0, 'eval_time': 0, 'success': False}

if len(sys.argv) < 2:
    print("Usage: run-phi3.py <task-file>"); sys.exit(1)

task_file = sys.argv[1]
with open(task_file) as f:
    task = json.load(f)

task_id = task.get('id', 'unknown')
desc = task.get('desc', 'No task')

print(f"🤖 Coder Agent (Phi3): {task_id}")
print(f"   Model: {MODEL} (2.2GB)")
print(f"   Task: {desc}")

task['status'] = 'running'
task['started_at'] = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())
with open(task_file, 'w') as f:
    json.dump(task, f)

system = "You are an expert Python programmer. Write clean, working code with comments. Only output code."
result = call_phi3(f"{system}\n\nTask: {desc}\n\nWrite Python code:")

if result['success']:
    out_dir = f"{WORKSPACE}/agent-output/{task_id}"
    os.makedirs(out_dir, exist_ok=True)
    out_file = f"{out_dir}/generated.py"
    with open(out_file, 'w') as f:
        f.write(f"#!/usr/bin/env python3\n# Generated by Phi3 Agent\n# Model: {MODEL}\n# Task: {desc}\n\n{result['response']}")
    os.chmod(out_file, 0o755)
    
    log_metrics(task_id, result['tokens_in'], result['tokens_out'], result['eval_time'])
    
    task.update({'status': 'done', 'completed_at': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
                 'result': f'Generated {out_file}', 'output_file': out_file})
    
    print(f"✅ Completed!")
    print(f"   Output: {out_file}")
    print(f"   Tokens: {result['tokens_in']} in, {result['tokens_out']} out")
    if result['eval_time'] > 0:
        print(f"   Speed: {result['tokens_out'] * 1000 // result['eval_time']} t/s")
    print(f"   Cost: $0.00 (LOCAL PHI3)")
else:
    task.update({'status': 'error', 'error': result['response']})
    print(f"❌ Failed: {result['response']}")

with open(task_file, 'w') as f:
    json.dump(task, f)
