#!/usr/bin/env python3
import os
import os.path
"""Real Coder Agent with Ollama Backend"""
import json, subprocess, sys, os, time

WORKSPACE = os.path.expanduser('~/.openclaw/workspace')

def log_metrics(task_id, agent, model, tokens_in, tokens_out, eval_time, cost):
    subprocess.run([f'{WORKSPACE}/llm-observability.sh', 'log', task_id, agent, model, 
                   str(tokens_in), str(tokens_out), str(eval_time), str(cost)], capture_output=True)

def call_ollama(prompt, model="mannix/qwen2.5-coder:0.5b-iq4_xs"):
    start = time.time()
    try:
        result = subprocess.run(['ollama', 'run', model], input=prompt, capture_output=True, text=True, timeout=60)
        elapsed = int((time.time() - start) * 1000)
        return {'response': result.stdout.strip(), 'tokens_in': len(prompt)//4, 
                'tokens_out': len(result.stdout)//4, 'eval_time': elapsed, 'success': result.returncode == 0}
    except Exception as e:
        return {'response': str(e), 'tokens_in': 0, 'tokens_out': 0, 'eval_time': 0, 'success': False}

if len(sys.argv) < 2:
    print("Usage: run-ollama.py <task-file>"); sys.exit(1)

task_file = sys.argv[1]
with open(task_file) as f:
    task_data = json.load(f)

task_id = task_data.get('id', 'unknown')
task_desc = task_data.get('desc', 'No task')

print(f"🤖 Coder Agent (Ollama): {task_id}")
print(f"   Task: {task_desc}")

task_data.update({'status': 'running', 'started_at': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())})
with open(task_file, 'w') as f:
    json.dump(task_data, f)

system = "You are an expert Python programmer. Write clean, working code. Only output code, no explanations."
result = call_ollama(f"{system}\n\nTask: {task_desc}\n\nWrite Python code:")

if result['success']:
    out_dir = f"{WORKSPACE}/agent-output/{task_id}"
    os.makedirs(out_dir, exist_ok=True)
    out_file = f"{out_dir}/generated.py"
    with open(out_file, 'w') as f:
        f.write(f"#!/usr/bin/env python3\n# Generated by Ollama Agent\n# Task: {task_desc}\n\n{result['response']}")
    os.chmod(out_file, 0o755)
    
    log_metrics(task_id, 'coder', 'mannix/qwen2.5-coder:0.5b', result['tokens_in'], result['tokens_out'], result['eval_time'], 0.0)
    
    task_data.update({'status': 'done', 'completed_at': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
                     'result': f'Generated {out_file}', 'output_file': out_file})
    
    print(f"✅ Completed: {task_id}")
    print(f"   Output: {out_file}")
    print(f"   Tokens: {result['tokens_in']} in, {result['tokens_out']} out")
    if result['eval_time'] > 0:
        print(f"   Speed: {result['tokens_out'] * 1000 // result['eval_time']} t/s")
    print(f"   Cost: $0.00 (LOCAL OLLAMA)")
else:
    task_data.update({'status': 'error', 'error': result['response']})
    print(f"❌ Failed: {result['response']}")

with open(task_file, 'w') as f:
    json.dump(task_data, f)
