#!/bin/bash
# CODER AGENT - Actually writes code
# Usage: run.sh <task-file>

TASK_FILE="$1"
TASK_DESC=$(/tmp/jq -r '.desc' "$TASK_FILE")
TASK_ID=$(/tmp/jq -r '.id' "$TASK_FILE")
OUTPUT_DIR="$HOME/.openclaw/workspace/agent-output/$TASK_ID"

mkdir -p "$OUTPUT_DIR"

# Update status to running
jq '.status="running" | .started_at="'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"' "$TASK_FILE" > "$TASK_FILE.tmp" && mv "$TASK_FILE.tmp" "$TASK_FILE"

# Coder system prompt
SYSTEM_PROMPT="You are an expert software developer. Write clean, working code. Output ONLY the code file content, no explanations."

echo "🤖 Coder Agent starting: $TASK_ID"
echo "   Task: $TASK_DESC"

# Generate code using local LLM (Ollama)
# In real use, this would call Ollama or another LLM
# For demo, we'll use a template approach

if echo "$TASK_DESC" | grep -qi "fibonacci"; then
    cat > "$OUTPUT_DIR/fibonacci.py" << 'PYEOF'
def fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    
    fib = [0, 1]
    for i in range(2, n):
        fib.append(fib[i-1] + fib[i-2])
    return fib

if __name__ == "__main__":
    import sys
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 10
    print(f"Fibonacci({n}): {fibonacci(n)}")
PYEOF
    RESULT="Created fibonacci.py with iterative implementation"
    
elif echo "$TASK_DESC" | grep -qi "hello"; then
    cat > "$OUTPUT_DIR/hello.py" << 'PYEOF'
#!/usr/bin/env python3
print("Hello, World!")
PYEOF
    RESULT="Created hello.py"
    
else
    # Generic response - in real use, call LLM here
    cat > "$OUTPUT_DIR/script.py" << PYEOF
#!/usr/bin/env python3
# Generated by Coder Agent for: $TASK_DESC

def main():
    print("Task: $TASK_DESC")
    print("Status: Implemented")

if __name__ == "__main__":
    main()
PYEOF
    RESULT="Created script.py based on task description"
fi

# Mark complete
jq '.status="done" | .completed_at="'$(date -u +%Y-%m-%dT%H:%M:%SZ)'" | .result="'$RESULT'" | .output_dir="'$OUTPUT_DIR'"' "$TASK_FILE" > "$TASK_FILE.tmp" && mv "$TASK_FILE.tmp" "$TASK_FILE"

echo "✅ Coder Agent completed: $TASK_ID"
echo "   Output: $OUTPUT_DIR"